version: '3'

services:
  mediawiki:
    image: wikimedia/mediawiki
    ports:
      - "8080:80"
    volumes:
      - wiki_data:/data
    environment:
      - MEDIAWIKI_SITE_SERVER=//localhost:8080
      - MEDIAWIKI_SITE_NAME=MediaWiki
      - MEDIAWIKI_SITE_LANG=en
      - MEDIAWIKI_ADMIN_USER=admin
      - MEDIAWIKI_ADMIN_PASS=rosebud
      - MEDIAWIKI_UPDATE=true
      - MEDIAWIKI_DB_TYPE=mysql
      - MEDIAWIKI_DB_USER=root
      - MEDIAWIKI_DB_HOST=mysql
      - MEDIAWIKI_DB_NAME=mediawiki
      - MEDIAWIKI_DB_PASSWORD=password
      - MEDIAWIKI_SLEEP=10
      - MEDIAWIKI_RESTBASE_URL=http://localhost:8080

  mysql:
    image: mysql:5.6.24
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password

volumes:
  wiki_data:
  mysql_data:
